# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-21 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichefrais', '0002_auto_20180421_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichefrais',
            name='etat',
            field=models.ForeignKey(on_delete=models.SET(1), to='fichefrais.Etat'),
        ),
    ]
