# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_job', models.CharField(max_length=15)),
                ('valeur_job', models.IntegerField()),
                ('home_job', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=40)),
                ('ville', models.CharField(blank=True, max_length=40)),
                ('cp', models.CharField(blank=True, max_length=5)),
                ('job', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
